title: "白米テック Blog"
email: hakumaitech@gmail.com
timezone: JST
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Sal
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  hakumai:
    name: 白米テック
    display_name: 白米
    avatar: 'assets/images/sal.png'
    email: hakumaitech@gmail.com
    web: https://hakumai.tech/
    twitter: https://twitter.com/hakumaitech
    description: "Author of Affiliates, a template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."

# Social
social:
  instagram: https://www.instagram.com/bootstrapstarter/
  facebook: https://www.facebook.com/bootstrapstartercom-346329609045284
  twitter: https://twitter.com/hakumaitech

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
