title: Hakumai.tech
author:
  name: HakumaiTech
  email: hakumaitech@gmail.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  フリーランスエンジニアとして活動しています。
  Ruby on Rails や Retool, Google App Script, ノーコードツールの開発・保守運用お任せ下さい。
  お仕事のご依頼やは hakumaitech@gmail.com までご連絡ください。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hakumai.tech/" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima

# As of November 2023, GitHub Pages still uses Minima 2.5.1 (https://pages.github.com/versions/).
# If you want to use the latest Minima version on GitHub Pages, use the following setting and
# add a line comment on "theme: minima" above.
#remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings
google_analytics: G-ZJRKTQ0N5N
header_pages:
  - about.md
  - contact.md

minima:
  skin: "solarized-light"
  date_format: "%Y-%m-%d %H:%M"
  social_links:
    - { platform: youtube,  user_url: "https://www.youtube.com/@HakumaiTech" }
    - { platform: github,  user_url: "https://github.com/HakumaiTech" }
